export type Question = {
  id: number;
  subject: 'Math' | 'Physics' | 'English' | 'Computer';
  question: string;
  options: { [key: string]: string };
  answer: string;
};

export const questions: Question[] = [
  // English
  {
    id: 26,
    subject: 'English',
    question: 'Medieval kingdoms did not become constitutional republics overnight; on the contrary, the change was _____.',
    options: { A: 'Unpopular', B: 'Gradual', C: 'Advantageous', D: 'Sufficient' },
    answer: 'B',
  },
  {
    id: 27,
    subject: 'English',
    question: 'What is the plural form of "crisis"?',
    options: { A: 'Crisises', B: 'Crises', C: 'Crisi', D: 'Crisum' },
    answer: 'B',
  },
  {
    id: 28,
    subject: 'English',
    question: 'The discovery of penicillin was a major breakthrough in medicine. Choose the synonym for "breakthrough".',
    options: { A: 'Failure', B: 'Hindrance', C: 'Advancement', D: 'Stagnation' },
    answer: 'C',
  },
  {
    id: 29,
    subject: 'English',
    question: 'A nerve cell is composed of a nucleus and cytoplasm.',
    options: { A: 'Made up', B: 'Surrounded', C: 'Found', D: 'Located' },
    answer: 'A',
  },
  {
    id: 30,
    subject: 'English',
    question: 'Which word means the same as "premature"?',
    options: { A: 'Late', B: 'Timely', C: 'Early', D: 'Delayed' },
    answer: 'C',
  },
  {
    id: 31,
    subject: 'English',
    question: 'He was very cautious in his approach to the problem. Choose the antonym for "cautious".',
    options: { A: 'Careful', B: 'Reckless', C: 'Prudent', D: 'Vigilant' },
    answer: 'B',
  },
  {
    id: 32,
    subject: 'English',
    question: 'People fishing on a lake must wait calmly so as not to scare the fish away.',
    options: { A: 'Considerately', B: 'Hungrily', C: 'Alertly', D: 'Quietly' },
    answer: 'D',
  },
  {
    id: 33,
    subject: 'English',
    question: 'The committee decided to ______ the meeting until next week.',
    options: { A: 'Adjourn', B: 'Convene', C: 'Hasten', D: 'Conclude' },
    answer: 'A',
  },
  {
    id: 34,
    subject: 'English',
    question: 'As a nerve cell is depolarized, it releases nerve impulses.',
    options: { A: 'Coincides', B: 'Emits', C: 'Pushes', D: 'Shields' },
    answer: 'B',
  },
  {
    id: 35,
    subject: 'English',
    question: 'When department stores have an oversupply of goods, they frequently cut prices to encourage sales.',
    options: { A: 'Conceal', B: 'Review', C: 'Damage', D: 'Reduce' },
    answer: 'D',
  },
  {
    id: 36,
    subject: 'English',
    question: 'Complete the sentence: "She is afraid ______ spiders."',
    options: { A: 'from', B: 'of', C: 'with', D: 'by' },
    answer: 'B',
  },
  {
    id: 37,
    subject: 'English',
    question: 'Choose the correct spelling:',
    options: { A: 'Occasion', B: 'Occassion', C: 'Ocassion', D: 'Occasionn' },
    answer: 'A',
  },
  {
    id: 38,
    subject: 'English',
    question: 'What is the part of speech for the word "fluently" in the sentence: "She speaks fluently in several languages."?',
    options: { A: 'Noun', B: 'Verb', C: 'Adjective', D: 'Adverb' },
    answer: 'D',
  },
  {
    id: 39,
    subject: 'English',
    question: 'Choose the word closest in meaning to "benevolent".',
    options: { A: 'Mean', B: 'Cruel', C: 'Kind', D: 'Selfish' },
    answer: 'C',
  },
  {
    id: 40,
    subject: 'English',
    question: 'Complete the sentence: "Neither John nor his friends ______ at the party."',
    options: { A: 'was', B: 'is', C: 'were', D: 'am' },
    answer: 'C',
  },
  {
    id: 41,
    subject: 'English',
    question: 'Which of the following is a sentence fragment?',
    options: { A: 'The dog barked loudly.', B: 'Running in the park.', C: 'She loves to read books.', D: 'He ate dinner quickly.' },
    answer: 'B',
  },
  {
    id: 42,
    subject: 'English',
    question: 'Identify the prepositional phrase in the sentence: "The cat slept under the table."',
    options: { A: 'The cat', B: 'Slept', C: 'Under the table', D: 'The table' },
    answer: 'C',
  },
  {
    id: 43,
    subject: 'English',
    question: 'What is the past participle of the verb "break"?',
    options: { A: 'Broke', B: 'Breaking', C: 'Broken', D: 'Breaks' },
    answer: 'C',
  },
  {
    id: 44,
    subject: 'English',
    question: 'Select the sentence with the correct subject-verb agreement.',
    options: { A: 'Each of the students have their books.', B: 'Each of the students has their books.', C: 'Each of the students were their books.', D: 'Each of the students are their books.' },
    answer: 'B',
  },
  {
    id: 45,
    subject: 'English',
    question: 'Which of these is an example of an oxymoron?',
    options: { A: 'Jumbo shrimp', B: 'Bright star', C: 'Blue sky', D: 'Fast car' },
    answer: 'A',
  },
  {
    id: 46,
    subject: 'English',
    question: 'Identify the conjunction in the sentence: "I wanted to go, but I was too tired."',
    options: { A: 'I', B: 'Wanted', C: 'But', D: 'Tired' },
    answer: 'C',
  },
  {
    id: 47,
    subject: 'English',
    question: 'Choose the word that means "to make less severe or serious".',
    options: { A: 'Exacerbate', B: 'Aggravate', C: 'Mitigate', D: 'Intensify' },
    answer: 'C',
  },
  {
    id: 48,
    subject: 'English',
    question: 'What is the correct relative pronoun to complete the sentence: "This is the book ______ I was looking for."',
    options: { A: 'who', B: 'whom', C: 'which', D: 'whose' },
    answer: 'C',
  },
  {
    id: 49,
    subject: 'English',
    question: 'The word "affect" is typically a:',
    options: { A: 'Noun', B: 'Verb', C: 'Adjective', D: 'Adverb' },
    answer: 'B',
  },
  {
    id: 50,
    subject: 'English',
    question: 'The principal\'s speech had a profound ______ on the students.',
    options: { A: 'affect', B: 'effect', C: 'effecting', D: 'affected' },
    answer: 'B',
  },
  // Math
  {
    id: 1,
    subject: 'Math',
    question: 'What is the product of the roots of the quadratic equation 2x<sup>2</sup> &minus; 5x + 3 = 0?',
    options: { A: '&minus;5/2', B: '5/2', C: '3/2', D: '&minus;3/2' },
    answer: 'C',
  },
  {
    id: 2,
    subject: 'Math',
    question: 'If A is a square matrix and A<sup>t</sup>=A then A is',
    options: { A: 'Involutory matrix', B: 'Idempotent matrix', C: 'Symmetric matrix', D: 'Hermitian matrix' },
    answer: 'C',
  },
  {
    id: 3,
    subject: 'Math',
    question: 'The domain of &radic;<span class="overline">x &minus; 2</span> is:',
    options: { A: 'x > 2', B: 'x < 2', C: 'x &ge; 2', D: 'x &le; 2' },
    answer: 'C',
  },
  {
    id: 4,
    subject: 'Math',
    question: 'If x=sin&theta; and y=cos&theta;, then what is x<sup>2</sup>+y<sup>2</sup>?',
    options: { A: '0', B: '1', C: '&minus;1', D: '2' },
    answer: 'B',
  },
  {
    id: 5,
    subject: 'Math',
    question: 'If A={1,2,3} and B={3,4,5}, then A&cap;B is:',
    options: { A: '{1,2,3,4,5}', B: '{3}', C: '{1,2,4,5}', D: '&empty;' },
    answer: 'B',
  },
  {
    id: 6,
    subject: 'Math',
    question: 'i<sup>16</sup> + i<sup>32</sup> &minus; i<sup>67</sup> =',
    options: { A: '&minus;1+i', B: '2+i', C: '1&minus;i', D: 'i' },
    answer: 'B',
  },
  {
    id: 7,
    subject: 'Math',
    question: 'The solution of e<sup>x</sup>=1 is:',
    options: { A: '0', B: '1', C: 'e', D: 'ln1' },
    answer: 'A',
  },
  {
    id: 8,
    subject: 'Math',
    question: 'In the matrix <table class="matrix"><tbody><tr><td>1</td><td>2</td><td>3</td></tr><tr><td>4</td><td>5</td><td>6</td></tr><tr><td>7</td><td>8</td><td>9</td></tr></tbody></table>, what is the element a<sub>23</sub>?',
    options: { A: '3', B: '6', C: '7', D: '8' },
    answer: 'B',
  },
  {
    id: 9,
    subject: 'Math',
    question: 'If the average of 8 students on a test is 77, if 4 of them got 73 marks, then what will be the sum of scores of other 4?',
    options: { A: '324', B: '211', C: '127', D: '623' },
    answer: 'A',
  },
  {
    id: 10,
    subject: 'Math',
    question: 'The value of 0! and 1! respectively are:',
    options: { A: '0 and 1', B: '1 and 1', C: '0 and -1', D: '1 and -1' },
    answer: 'B',
  },
  {
    id: 11,
    subject: 'Math',
    question: 'The set of all real numbers is denoted by:',
    options: { A: 'N', B: 'Z', C: 'Q', D: 'R' },
    answer: 'D',
  },
  {
    id: 12,
    subject: 'Math',
    question: 'The matrix <table class="matrix"><tbody><tr><td>0</td><td>0</td></tr><tr><td>0</td><td>0</td></tr></tbody></table> is a:',
    options: { A: 'Identity matrix', B: 'Scalar matrix', C: 'Zero matrix', D: 'Unit matrix' },
    answer: 'C',
  },
  {
    id: 13,
    subject: 'Math',
    question: 'The value of the determinant of a matrix with two identical rows is:',
    options: { A: '0', B: '1', C: '7', D: '&minus;1' },
    answer: 'A',
  },
  {
    id: 14,
    subject: 'Math',
    question: 'The discriminant of a quadratic equation ax<sup>2</sup>+bx+c=0 is:',
    options: { A: 'b<sup>2</sup>&minus;4ac', B: '&radic;<span class="overline">b<sup>2</sup>&minus;4ac</span>', C: '&minus;b&plusmn;&radic;<span class="overline">b<sup>2</sup>&minus;4ac</span>', D: '(&minus;b&plusmn;&radic;<span class="overline">b<sup>2</sup>&minus;4ac</span>)/2a' },
    answer: 'A',
  },
  {
    id: 15,
    subject: 'Math',
    question: 'If A=<table class="matrix"><tbody><tr><td>1</td><td>0</td></tr><tr><td>0</td><td>1</td></tr></tbody></table>, then A is an:',
    options: { A: 'Zero Matrix', B: 'Scalar Matrix', C: 'Identity Matrix', D: 'Diagonal Matrix' },
    answer: 'C',
  },
  {
    id: 16,
    subject: 'Math',
    question: 'Solution of the equation 12<sup>x</sup> + 18<sup>y</sup> = 468 is',
    options: { A: 'x=2, y=2', B: 'x=1, y=2', C: 'x=2/3, y=1/3', D: 'x=4/3, y=1/5' },
    answer: 'A',
  },
  {
    id: 17,
    subject: 'Math',
    question: 'If A is a square matrix and A<sup>2</sup>=A then A is',
    options: { A: 'Involutory matrix', B: 'Idempotent matrix', C: 'Symmetric matrix', D: 'Hermitian matrix' },
    answer: 'B',
  },
  {
    id: 18,
    subject: 'Math',
    question: 'If x<sup>2</sup>=49, then x=',
    options: { A: '7', B: '&plusmn;7', C: '&minus;7', D: '1/7' },
    answer: 'B',
  },
  {
    id: 19,
    subject: 'Math',
    question: 'The degree of the polynomial 3x<sup>4</sup>&minus;2x<sup>2</sup>+5 is:',
    options: { A: '1', B: '2', C: '3', D: '4' },
    answer: 'D',
  },
  {
    id: 20,
    subject: 'Math',
    question: 'What is the value of log<sub>10</sub>(100)?',
    options: { A: '1', B: '2', C: '10', D: '100' },
    answer: 'B',
  },
  {
    id: 21,
    subject: 'Math',
    question: 'If two matrices A and B are multiplied, the number of columns in A must be equal to the number of ______ in B.',
    options: { A: 'rows', B: 'columns', C: 'elements', D: 'non-zero elements' },
    answer: 'A',
  },
  {
    id: 22,
    subject: 'Math',
    question: 'If z = x + iy then |<span class="overline">z</span>| =',
    options: { A: '&radic;<span class="overline">x<sup>2</sup> &minus; y<sup>2</sup></span>', B: '&radic;<span class="overline">x<sup>2</sup> + y<sup>2</sup></span>', C: '&minus;&radic;<span class="overline">x<sup>2</sup> + y<sup>2</sup></span>', D: '&minus;&radic;<span class="overline">x<sup>2</sup> &minus; y<sup>2</sup></span>' },
    answer: 'B',
  },
  {
    id: 23,
    subject: 'Math',
    question: 'The number of terms in the expansion of (a+b)<sup>n</sup> is:',
    options: { A: 'n', B: 'n-1', C: 'n+1', D: '2n' },
    answer: 'C',
  },
  {
    id: 24,
    subject: 'Math',
    question: 'The solution set of x<sup>2</sup>&minus;9=0 is:',
    options: { A: '{3}', B: '{-3}', C: '{3, -3}', D: '{9}' },
    answer: 'C',
  },
  {
    id: 25,
    subject: 'Math',
    question: 'If A=<table class="matrix"><tbody><tr><td>2</td><td>0</td></tr><tr><td>0</td><td>2</td></tr></tbody></table>, then A is a:',
    options: { A: 'Zero Matrix', B: 'Scalar Matrix', C: 'Identity Matrix', D: 'Diagonal Matrix' },
    answer: 'B',
  },
  // Physics
  {
    id: 51,
    subject: 'Physics',
    question: 'The sum of kinetic and potential energy is called:',
    options: { A: 'Electrical energy', B: 'Thermal energy', C: 'Mechanical energy', D: 'Chemical energy' },
    answer: 'C',
  },
  {
    id: 52,
    subject: 'Physics',
    question: 'Which device converts mechanical energy into electrical energy?',
    options: { A: 'Motor', B: 'Generator', C: 'Transformer', D: 'Resistor' },
    answer: 'B',
  },
  {
    id: 53,
    subject: 'Physics',
    question: 'What is the SI unit of pressure?',
    options: { A: 'Newton', B: 'Joule', C: 'Pascal', D: 'Watt' },
    answer: 'C',
  },
  {
    id: 54,
    subject: 'Physics',
    question: 'Which of these waves does NOT require a medium for propagation?',
    options: { A: 'Sound waves', B: 'Water waves', C: 'Light waves', D: 'Seismic waves' },
    answer: 'C',
  },
  {
    id: 55,
    subject: 'Physics',
    question: 'What is the wavelength of a sound wave with a frequency of 200 Hz and a speed of 340 m/s?',
    options: { A: '0.588 m', B: '1.7 m', C: '68 m', D: '68000 m' },
    answer: 'B',
  },
  {
    id: 56,
    subject: 'Physics',
    question: 'Angular momentum is defined as:',
    options: { A: 'r&#x20D7; + p&#x20D7;', B: 'p&#x20D7; &times; r&#x20D7;', C: 'r&middot;p', D: 'r&#x20D7; &times; p&#x20D7;' },
    answer: 'D',
  },
  {
    id: 57,
    subject: 'Physics',
    question: 'The phenomenon responsible for the twinkling of stars is:',
    options: { A: 'Reflection', B: 'Dispersion', C: 'Atmospheric refraction', D: 'Total internal reflection' },
    answer: 'C',
  },
  {
    id: 58,
    subject: 'Physics',
    question: 'What is the total resistance of two resistors, 10 &Omega; and 20 &Omega;, connected in series?',
    options: { A: '5 &Omega;', B: '10 &Omega;', C: '20 &Omega;', D: '30 &Omega;' },
    answer: 'D',
  },
  {
    id: 59,
    subject: 'Physics',
    question: 'If focal length is increased two times, what happens to the power of the lens?',
    options: { A: 'Power becomes 4 times', B: 'Power becomes half', C: 'Power becomes double', D: 'Power remains unchanged' },
    answer: 'B',
  },
  {
    id: 60,
    subject: 'Physics',
    question: 'What is the SI unit of electric charge?',
    options: { A: 'Volt', B: 'Ampere', C: 'Coulomb', D: 'Ohm' },
    answer: 'C',
  },
  {
    id: 61,
    subject: 'Physics',
    question: 'What is the SI unit of frequency?',
    options: { A: 'Second', B: 'Meter', C: 'Hertz', D: 'Joule' },
    answer: 'C',
  },
  {
    id: 62,
    subject: 'Physics',
    question: 'The acceleration of a body moving with uniform velocity is:',
    options: { A: 'Positive', B: 'Negative', C: 'Zero', D: 'Constant' },
    answer: 'C',
  },
  {
    id: 63,
    subject: 'Physics',
    question: 'What is the SI unit of temperature?',
    options: { A: 'Celsius', B: 'Fahrenheit', C: 'Kelvin', D: 'Rankine' },
    answer: 'C',
  },
  {
    id: 64,
    subject: 'Physics',
    question: 'The unit of work is:',
    options: { A: 'Watt', B: 'Newton', C: 'Joule', D: 'Second' },
    answer: 'C',
  },
  {
    id: 65,
    subject: 'Physics',
    question: 'What happens to the potential energy of an object as it falls?',
    options: { A: 'Increases', B: 'Decreases', C: 'Remains constant', D: 'Converts to thermal energy only' },
    answer: 'B',
  },
  {
    id: 66,
    subject: 'Physics',
    question: 'The property of a material to resist the flow of electric current is called:',
    options: { A: 'Conductance', B: 'Capacitance', C: 'Resistance', D: 'Inductance' },
    answer: 'C',
  },
  {
    id: 67,
    subject: 'Physics',
    question: 'Which of the following equations represents Power?',
    options: { A: 'F*V', B: 'F/V', C: 'F+V', D: 'F-A' },
    answer: 'A',
  },
  {
    id: 68,
    subject: 'Physics',
    question: 'According to Ohm\'s Law, if voltage increases and resistance remains constant, current will:',
    options: { A: 'Increase', B: 'Decrease', C: 'Remain the same', D: 'Be zero' },
    answer: 'A',
  },
  {
    id: 69,
    subject: 'Physics',
    question: 'A magnifying glass is a type of which lens?',
    options: { A: 'Concave lens', B: 'Convex lens', C: 'Plano-concave lens', D: 'Cylindrical lens' },
    answer: 'B',
  },
  {
    id: 70,
    subject: 'Physics',
    question: 'Which of the following is a fundamental quantity?',
    options: { A: 'Force', B: 'Work', C: 'Time', D: 'Power' },
    answer: 'C',
  },
  {
    id: 71,
    subject: 'Physics',
    question: 'The term "inertia" is directly related to an object\'s:',
    options: { A: 'Velocity', B: 'Acceleration', C: 'Mass', D: 'Force' },
    answer: 'C',
  },
  {
    id: 72,
    subject: 'Physics',
    question: 'The phenomenon of light bouncing back from a surface is called:',
    options: { A: 'Refraction', B: 'Reflection', C: 'Diffraction', D: 'Dispersion' },
    answer: 'B',
  },
  {
    id: 73,
    subject: 'Physics',
    question: 'The bending of light as it passes from one medium to another is called:',
    options: { A: 'Reflection', B: 'Refraction', C: 'Dispersion', D: 'Absorption' },
    answer: 'B',
  },
  {
    id: 74,
    subject: 'Physics',
    question: 'If a force of 10 N is applied to an object with a mass of 2 kg, what is the acceleration produced?',
    options: { A: '0.2 m/s&sup2;', B: '2 m/s&sup2;', C: '5 m/s&sup2;', D: '20 m/s&sup2;' },
    answer: 'C',
  },
  {
    id: 75,
    subject: 'Physics',
    question: 'The speed of sound in air at 0&deg;C is approximately:',
    options: { A: '331 m/s', B: '343 m/s', C: '1500 m/s', D: '5000 m/s' },
    answer: 'A',
  },
  // Computer
  {
    id: 76,
    subject: 'Computer',
    question: 'What is the primary function of a firewall?',
    options: { A: 'To increase internet speed', B: 'To block unauthorized access to a network', C: 'To store data', D: 'To process graphics' },
    answer: 'B',
  },
  {
    id: 77,
    subject: 'Computer',
    question: 'What does "GUI" stand for?',
    options: { A: 'General User Interface', B: 'Graphical User Interface', C: 'Grand Unified Interface', D: 'Graphic Utility Index' },
    answer: 'B',
  },
  {
    id: 78,
    subject: 'Computer',
    question: 'What does "URL" stand for?',
    options: { A: 'Uniform Resource Locator', B: 'Universal Remote Link', C: 'User Resource Language', D: 'United Resource Locator' },
    answer: 'A',
  },
  {
    id: 79,
    subject: 'Computer',
    question: 'Which of these is a volatile memory?',
    options: { A: 'ROM', B: 'Hard Drive', C: 'RAM', D: 'SSD' },
    answer: 'C',
  },
  {
    id: 80,
    subject: 'Computer',
    question: 'What is the purpose of a router in a network?',
    options: { A: 'To store data', B: 'To print documents', C: 'To connect different networks and direct data traffic', D: 'To display images' },
    answer: 'C',
  },
  {
    id: 81,
    subject: 'Computer',
    question: '"RAM" stands for:',
    options: { A: 'Read Access Memory', B: 'Random Access Memory', C: 'Read-Only Access Memory', D: 'Random Application Memory' },
    answer: 'B',
  },
  {
    id: 82,
    subject: 'Computer',
    question: 'What is the full form of "WWW"?',
    options: { A: 'World Wide Web', B: 'World Web Wide', C: 'Web World Wide', D: 'Wide World Web' },
    answer: 'A',
  },
  {
    id: 83,
    subject: 'Computer',
    question: 'What is a "pixel"?',
    options: { A: 'A unit of sound', B: 'A tiny dot on a display screen', C: 'A type of computer virus', D: 'A network cable' },
    answer: 'B',
  },
  {
    id: 84,
    subject: 'Computer',
    question: 'Which port is commonly used to connect a monitor to a computer?',
    options: { A: 'USB', B: 'Ethernet', C: 'HDMI', D: 'PS/2' },
    answer: 'C',
  },
  {
    id: 85,
    subject: 'Computer',
    question: 'What is the complement of the XOR operation?',
    options: { A: 'XNOR', B: 'AND', C: 'OR', D: 'NOT' },
    answer: 'A',
  },
  {
    id: 86,
    subject: 'Computer',
    question: 'Which of the following is a programming language?',
    options: { A: 'HTML', B: 'CSS', C: 'Python', D: 'JPEG' },
    answer: 'C',
  },
  {
    id: 87,
    subject: 'Computer',
    question: 'The smallest unit of data in a computer is:',
    options: { A: 'Byte', B: 'Kilobyte', C: 'Bit', D: 'Megabyte' },
    answer: 'C',
  },
  {
    id: 88,
    subject: 'Computer',
    question: 'What is software that allows a user to access, retrieve, and view information on the World Wide Web?',
    options: { A: 'Operating system', B: 'Web browser', C: 'Word processor', D: 'Spreadsheet' },
    answer: 'B',
  },
  {
    id: 89,
    subject: 'Computer',
    question: 'What does "IBM" stand for?',
    options: { A: 'International Business Machines', B: 'Integrated Business Management', C: 'Internet-Based Management', D: 'Informational Business Model' },
    answer: 'A',
  },
  {
    id: 90,
    subject: 'Computer',
    question: 'What is the process of finding and fixing errors in a program?',
    options: { A: 'Compiling', B: 'Debugging', C: 'Executing', D: 'Testing' },
    answer: 'B',
  },
  {
    id: 91,
    subject: 'Computer',
    question: 'Which of the following is an input device?',
    options: { A: 'Printer', B: 'Monitor', C: 'Keyboard', D: 'Speaker' },
    answer: 'C',
  },
  {
    id: 92,
    subject: 'Computer',
    question: 'A network that connects computers within a limited area such as a home or office is called a:',
    options: { A: 'WAN', B: 'MAN', C: 'LAN', D: 'PAN' },
    answer: 'C',
  },
  {
    id: 93,
    subject: 'Computer',
    question: 'Which component of a computer stores long-term data even when the computer is turned off?',
    options: { A: 'RAM', B: 'CPU', C: 'Hard Drive', D: 'Cache Memory' },
    answer: 'C',
  },
  {
    id: 94,
    subject: 'Computer',
    question: 'The term "CPU" stands for:',
    options: { A: 'Central Power Unit', B: 'Computer Processing Unit', C: 'Central Processing Unit', D: 'Control Panel Unit' },
    answer: 'C',
  },
  {
    id: 95,
    subject: 'Computer',
    question: 'A collection of related information stored and organized for easy access and retrieval is called a:',
    options: { A: 'Spreadsheet', B: 'Database', C: 'Presentation', D: 'Document' },
    answer: 'B',
  },
  {
    id: 96,
    subject: 'Computer',
    question: 'What is a "byte" composed of?',
    options: { A: '4 bits', B: '8 bits', C: '16 bits', D: '32 bits' },
    answer: 'B',
  },
  {
    id: 97,
    subject: 'Computer',
    question: 'What is the main purpose of an antivirus software?',
    options: { A: 'To speed up the computer', B: 'To protect against malware and viruses', C: 'To create documents', D: 'To play games' },
    answer: 'B',
  },
  {
    id: 98,
    subject: 'Computer',
    question: 'Which of the following is an operating system?',
    options: { A: 'Microsoft Word', B: 'Google Chrome', C: 'Windows', D: 'Adobe Photoshop' },
    answer: 'C',
  },
  {
    id: 99,
    subject: 'Computer',
    question: 'What does "IP" stand for in the context of computer networks?',
    options: { A: 'Internet Protocol', B: 'Internal Process', C: 'Information Packet', D: 'Integrated Program' },
    answer: 'A',
  },
  {
    id: 100,
    subject: 'Computer',
    question: 'Which type of software is used to create and edit text documents?',
    options: { A: 'Spreadsheet software', B: 'Presentation software', C: 'Word processing software', D: 'Database software' },
    answer: 'C',
  },
];
